apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  labels:
    app: kibana
data:
  kibana.yml: |-
    server.host: 0.0.0.0
    server.ssl.enabled: false
    elasticsearch: 
      hosts: ${ELASTICSEARCH_HOSTS}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:7.16.1
        ports:
        - containerPort: 5601
          name: kibana-svc
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://10.100.49.167:9200"
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config/kibana.yml
          readOnly: true
          subPath: kibana.yml
      volumes:
      - name: config
        configMap:
          name: kibana-config
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  labels:
    service: kibana-svc
spec:
  type: NodePort
  ports:
  - port: 5601
    name: kibana-svc
  selector:
    app: kibana