version: '3.4'

networks:
  hclarticleserviceapi_dev:
    external: true

services:
  hcl.commentserver.api:
    image: ${DOCKER_REGISTRY-}hclcommentserverapi
    depends_on: 
      - app_db_hcl_comment
    container_name: HCL.CommentServer
    build:
      context: .
      dockerfile: HCL.CommentServer.API/Dockerfile
    environment:
      - ElasticConfiguration__Uri=http://elasticsearch:9200
      - ConnectionStrings__NpgConnectionString=User Id=postgres; Password=pg; Server=app_db_hcl_comment; Port=5432; Database=HCL_Comment; IntegratedSecurity=true; Pooling=true;
    networks:
      - hclarticleserviceapi_dev

  app_db_hcl_comment: 
    image: postgres:latest
    container_name: app_db_hcl_comment
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg
      - POSTGRES_DB=HCL_Comment
    ports:
      - "5493:5432"
    restart: always
    volumes:
      - app_data_comment:/var/lib/postgresql/data_comment
    networks:
      - hclarticleserviceapi_dev

  elasticsearch:
   container_name: elasticsearch
   image: elasticsearch:7.16.1
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
   networks:
      - hclarticleserviceapi_dev

  kibana:
   container_name: kibana
   image: kibana:7.16.1
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://localhost:9200
   networks:
      - hclarticleserviceapi_dev

volumes:
  app_data_comment:
  elasticsearch-data: