// <auto-generated />
using System;
using HCL.CommentServer.API.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HCL.CommentServer.API.DAL.Migrations
{
    [DbContext(typeof(CommentAppDBContext))]
    [Migration("20230504131148_addColumn")]
    partial class addColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HCL.CommentServer.API.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("pk_comment_id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("account_id");

                    b.Property<string>("ArticleId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("article_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("mark");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("comments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
